// Generated by CoffeeScript 1.6.3
(function() {
  var WebServer, express, fs, path, pjson;

  express = require('express');

  path = require('path');

  fs = require('fs');

  pjson = require('../../package.json');

  module.exports = WebServer = (function() {
    function WebServer(_app) {
      this._app = _app;
      this._webapp = express();
      this._webapp.use(express.methodOverride());
      this._registerRoutes();
    }

    WebServer.prototype._registerRoutes = function() {
      var _this = this;
      this._webapp.use('/', express["static"](path.join(__dirname, '..', '..', 'web')));
      this._webapp.get('/api/version', function(req, res) {
        return res.send({
          success: true,
          version: pjson.version
        });
      });
      this._webapp.get('/api/shares', function(req, res) {
        var shares;
        shares = _this._app.getTracker().getShares('json');
        return res.send({
          success: true,
          payload: shares
        });
      });
      return this._webapp.get('/api/flush/:id', function(req, res) {
        _this._app.getTracker().deleteShare(req.params.id);
        return res.send({
          success: true
        });
      });
    };

    WebServer.prototype.listen = function(port, address) {
      this._webapp.listen(port, address);
      return this._app.getLogger().info('Web server listening on ' + address + ':' + port);
    };

    return WebServer;

  })();

}).call(this);
