// Generated by CoffeeScript 1.6.3
(function() {
  var errors;

  errors = require('./errors');

  module.exports = {
    ip_ntoa: function(ip) {
      return (ip & 0xFF) + '.' + ((ip >> 8) & 0xFF) + '.' + ((ip >> 16) & 0xFF) + '.' + ((ip >> 24) & 0xFF);
    },
    ip_aton: function(ip) {
      var parts;
      parts = ip.split('.');
      if (parts.length !== 4) {
        throw new errors.ParameterError('Invalid IP specified.');
      }
      return ((parseInt(parts[3], 10) << 24) >>> 0) + ((parseInt(parts[2], 10) << 16) >>> 0) + ((parseInt(parts[1], 10) << 8) >>> 0) + (parseInt(parts[0], 10) >>> 0);
    }
  };

}).call(this);
