// Generated by CoffeeScript 1.6.3
(function() {
  var SyncIO, app, path;

  path = require('path');

  SyncIO = require('./lib/SyncIO');

  app = new SyncIO();

  app.loadConfig(path.join(__dirname, '../config.json'));

  app.run();

}).call(this);
