// Generated by CoffeeScript 1.6.3
(function() {
  var misc;

  misc = require('../utils/misc');

  module.exports = function(app, packetData, peer) {
    var answerData, peerData, peerIdentifierHex, shareIdentifierHex;
    if ((packetData.share == null) || (packetData.peer == null) || (packetData.la == null)) {
      app.getLogger().warning('Discarded packet with type \'get_peers\' because of missing data');
      return;
    }
    peerIdentifierHex = packetData.peer.toString('hex');
    shareIdentifierHex = packetData.share.toString('hex');
    peerData = {
      id: peerIdentifierHex,
      binId: packetData.peer,
      local: {
        address: misc.ip_ntoa(packetData.la.readUInt32LE(0)),
        port: packetData.la.readUInt16LE(4)
      },
      binLocal: packetData.la,
      remote: {
        address: peer.address,
        port: peer.port
      },
      binRemote: misc.bts_addr(peer.address, peer.port)
    };
    app.getTracker().announceShare(shareIdentifierHex);
    app.getTracker().announcePeer(shareIdentifierHex, peerData);
    answerData = {
      m: 'peers',
      share: packetData.share,
      time: Math.round((new Date()).getTime() / 1000),
      ea: peerData.binRemote,
      peers: app.getTracker().getPeers(shareIdentifierHex, 'btsync')
    };
    return app.getSyncServer().sendAnswer(answerData, peer);
  };

}).call(this);
